---
- hosts: app
  become: yes
  tasks:
     - name: Disable SELinux 
       lineinfile:
         path: /etc/selinux/config
         regexp: '^SELINUX='
         line: 'SELINUX=disabled'


     - name: Install EPEL meta package
       yum:
         name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
         state: present
     
     - name: Add repository
       yum_repository:
         name: nginx
         description: nginx YUM repo
         file: nginx
         baseurl: http://nginx.org/packages/centos/7/$basearch/
         gpgcheck: yes
         gpgkey: https://nginx.org/keys/nginx_signing.key
     
     - name: Install nginx, python36 and other requirements
       yum: 
        name:
         - libselinux-python
         - gcc
         - python36-devel
         - git
         - nginx
         - python36
         - python36-pip
         - python-setuptools
         - python-virtualenv
#         - uwsgi 
         - uwsgi-plugin-python36
        state: present
#       update_cache: yes
#       enablerepo: epel

     - name: Disable SELinux 
       selinux:
        state: disabled



     - name: Copy nginx config 
       command: cp -f /vagrant/cfg/default.conf /etc/nginx/conf.d
     - command: cp -f /vagrant/cfg/nginx.conf /etc/nginx

     - name: Copy UWSGI config 
       command: cp /vagrant/cfg/uwsgi_app.ini /etc/uwsgi.d/
       become_user: uwsgi
     
     - name: Setting UWSGI config files attributes
       file:
         path: /etc/uwsgi.d/
         owner: uwsgi
         group: uwsgi
         mode: 01751
         recurse: yes


     
     - name: Setting NGINX config files attributes
       file:
         path: /etc/nginx
         owner: nginx
         group: nginx
         mode: 751
         recurse: yes


     - git:
         repo: https://bitbucket.org/m_baranov/test-app/src/master/
         dest: /opt/app
     - name: Configuring APP  
       lineinfile:
         path: /opt/app/app/config.py
         regexp: 'postgresql://worker:worker@localhost/app'
         line: "    SQLALCHEMY_DATABASE_URI='postgresql://app_user:app_password@192.168.0.10/app'"

     - file:
         path: /opt/app
         owner: uwsgi
         group: uwsgi
         mode: 0770
         recurse: yes


     - file:
         path: /run/uwsgi
         owner: uwsgi
         group: nginx
         mode: 0777
         recurse: yes

     - file:
         path: /opt/app/app/static
         owner: nginx
         group: nginx
         mode: 0760
         recurse: yes
#         state: directory
     - name: Add user nginx to uwsgi group
       user:
        name: nginx
        groups: uwsgi
     
     - name: Install requirements
       pip: 
         requirements: /opt/app/app/requirements.txt
         virtualenv: /opt/app/venv
         virtualenv_python: python3.6
     - name: Make migrtion
       shell: "cd /opt/app && source venv/bin/activate && cd app/ && FLASK_APP=app.py flask db upgrade"

     - name: Start and enable nginx
       service: name=nginx state=started enabled=yes
     - name: Start and enable uwsgi
       service: name=uwsgi state=started enabled=yes
