---
- hosts: db1
  become: yes
  tasks:
# These tasks install http and the php modules.
     - name: Install postgresql meta package
       yum:
         name: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm
         state: present
     
     - name: Install postgresql
       yum: 
        name:
         - postgresql96-server
         - python-psycopg2
        state: present

     - name: Sync PGSQ with master
       command: "rm -rf /var/lib/pgsql/9.6/data/"
     - command: "mkdir /var/lib/pgsql/9.6/data"
     - command: "pg_basebackup -h 192.168.0.10 -D /var/lib/pgsql/9.6/data/ -R -P -U postgres --xlog-method=stream"
     
     - lineinfile:
         path: /var/lib/pgsql/9.6/data/recovery.conf
         line: "trigger_file = '/var/lib/pgsql/9.6/data/trigger_file'"
         create: no
      

     - name: Setting PGSQL config files attributes
       file:
         path: /var/lib/pgsql/9.6/data/
         owner: postgres
         group: postgres
         mode: 0700
         recurse: yes
    

     - name: Start and enable postgresql
       service: name=postgresql-9.6 state=started enabled=yes
     
     
