---
# These tasks are responsible for copying the latest dev/production code from
# the version control system.

- name: Copy zabbix config
  template: src=zabbix.conf.php.j2 dest=/etc/zabbix/web/zabbix.conf.php

- name: Copy zabbix-server config
  template: src=zabbix_server.conf.j2 dest=/etc/zabbix/zabbix_server.conf

- name: set atributes
  file:
   path: "/etc/zabbix"
   owner: zabbix
   group: nginx
   state: directory 
   recurse: yes

#- name: Creates the index.php file
#  template: src=index.php.j2 dest=/var/www/index.php
