---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  become: yes
  roles:
    - common
- name: apply common configuration to all nodes
  hosts: db
  become: yes
  roles:
    - db_master
- name: apply common configuration to all nodes
  hosts: db1
  become: yes
  roles:
    - db_slave
- name: apply common configuration to all nodes
  hosts: bal
  become: yes
  roles:
    - bal
- name: apply common configuration to all nodes
  hosts: app, app1
  become: yes
  roles: 
    - web
   
  
