---
# This playbook contains common plays that will be run on all nodes.
- name: RAW install python 
  raw: yum -y install python

- name: Disable SELinux 
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'

- name: Install EPEL meta package
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Install ntp
  yum: name=ntp state=present
  tags: ntp

- name: Install common dependencies
  yum: 
   name:
    - libselinux-python
    - libsemanage-python
    - firewalld
    - python-psycopg2
   state: installed

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntpd state=started enabled=yes
  tags: ntp
