---
- name: Set PostgreSQL environment variables.
  template:
    src: postgresql-10.service.j2
    dest:  /usr/lib/systemd/system/postgresql-10.service
    mode: 0644

- name: Set PostgreSQL environment variables.
  template:
    src: postgres.sh.j2
    dest: /etc/profile.d/postgres.sh
    mode: 0644
   

- name: Ensure PostgreSQL data directory exists.
  file:
    path: "{{ postgresql_data_dir }}"
    owner: postgres
    group: postgres
    state: directory
    mode: 0700

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: pgdata_dir_version
  become: yes
  become_user: postgres

- name: Ensure PostgreSQL database is initialized.
  command:  "{{ postgresql_bin_path }}/initdb -D {{ postgresql_data_dir }}"
  when: not pgdata_dir_version.stat.exists
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  notify: start postgresql

- name: start postgresql
  service: name=postgresql-10 daemon_reload=yes state=started enabled=yes

- name: Copy postgresql.conf.
  template:
    src: postgresql.conf.j2
    dest: "{{ postgresql_data_dir }}/postgresql.conf"
    mode: 0644
  notify: restart postgresql

- name: Copy pg_hba.conf.j2
  template:
    src: pg_hba.conf.j2
    dest: "{{ postgresql_data_dir }}/pg_hba.conf"
    mode: 0644

- name: reloaded postgresql
  shell: "{{ postgresql_bin_path }}/pg_ctl -D {{ postgresql_data_dir }} reload"
  become: yes
  become_user: postgres
  args:
        executable: /bin/bash

#- name: create postgresq user for zabbix
#  postgresql_user:
##     db: zabbix
#     name: zabbix
#     password: "!_zabbix"
#     encrypted: yes
#     role_attr_flags:  SUPERUSER

#- name: create db for zabbix 
#  postgresql_db:
#     name: zabbix
#     encoding: UTF-8
#     lc_collate: en_US.UTF-8
#     lc_ctype: en_US.UTF-8
#     template: template0
#     owner: zabbix
#     state: present
#
#- raw: find /usr/share/doc/zabbix* -name "create*.gz" -exec gunzip -c {} > /home/azz/create.sql \;
#  args: /bin/bash

#- postgresql_db:
#    name: zabbix
#    login_user: "{{ postgresql_user_zabbix }}"
#    login_password: "{{ postgresql_zabbix_password }}"
#    state: restore
#    target: /home/azz/create.sql
#  
#- name: Start and enable PostgreSQL Service
#  service: name=postgresql-10 daemon_reload=yes state=started enabled=yes

